# Generated by Django 4.1.7 on 2023-04-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_todo', '0002_todo_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
