# Generated by Django 4.1.7 on 2023-03-24 20:22

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('musaaj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
        ),
    ]
