# Generated by Django 4.1.7 on 2023-03-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musaaj', '0003_alter_audiomodel_id_alter_photomodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
